@baseUrl = https://https://crud-agenda-2hjq.onrender.com
### render request links
### Gets all contacts
GET {{baseUrl}}/contacts HTTP/1.1

### Gets a contact by id
GET {{baseUrl}}/contacts/65b58ffc33c4a3da393a8dfc HTTP/1.1

### Create a contact
POST {{baseUrl}}/contacts/
Content-Type: application/json

{
    "name": "client name",
    "relation": "family",
    "birthday": "2000-01-01",
    "email": "new@contact.com",
    "phone": "+529984834032"
}

### Updating a contact by Id, you can send all data or just the columns to update
PUT {{baseUrl}}/contacts/65b578286cf60d9e0eb49224
Content-Type: application/json

{
    "name": "Miguel Prot",
    "relation": "family",
    "birthday": "1993-20-02",
    "phone": "9981212135",
    "email": "prot.garcia@gmail.com"
}

### Deleting an specific contact
DELETE {{baseUrl}}/contacts/65b58ffc33c4a3da393a8dfc